"""empty message

Revision ID: 35d6a1801152
Revises: a8570df43e7a
Create Date: 2022-10-05 16:48:58.537652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d6a1801152'
down_revision = 'a8570df43e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('form', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'form')
    # ### end Alembic commands ###
