"""empty message

Revision ID: a8570df43e7a
Revises: fd43077a2439
Create Date: 2022-09-29 12:07:07.704857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8570df43e7a'
down_revision = 'fd43077a2439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('telephone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'telephone')
    # ### end Alembic commands ###
